name: Build APK (Ionic 8 + Capacitor)

on:
  push:
    branches: [ main ] # atau nama branch kamu

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Build Ionic
      run: npm run build

    - name: Copy Web to Android
      run: npx cap sync android

    - name: Give gradlew execute permission
      run: chmod +x android/gradlew

    - name: Setup Java for Android
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v3.1.3 # <- versi stabil
      with:
        name: app-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
