name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.12.0' # Atau versi Node.js yang sesuai dengan proyek Anda

    - name: Install dependencies
      run: npm install

    - name: Build Ionic/Angular app
      run: npm run build -- --prod

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17' # Atau versi Java yang sesuai dengan proyek Anda

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Build Android APK
      run: |
        cd android
        # Jika Anda menghasilkan keystore, uncomment baris di bawah dan sesuaikan
        # echo "signingConfigs { release { storeFile file('my-release-key.keystore') storePassword 'your_store_password' keyAlias 'my-alias' keyPassword 'your_key_password' }}" >> app/build.gradle
        ./gradlew assembleDebug # Atau assembleRelease untuk build release

    - name: Upload APK
      uses: actions/upload-artifact@v3.1.3
      with:
        name: android-app-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
